name: Production Deploy

on:
  workflow_dispatch:
    inputs:
      api_selection:
        description: "Selecione a API"
        required: true
        type: choice
        options:
          - Primeira API
          - Segunda API

      api_version:
        description: "Versão da imagem (ex: 1.0.0)"
        required: true
        type: string

jobs:
  validate_environment:
    name: Environment Validation
    runs-on: ubuntu-latest
    outputs:
      dotnet_project: ${{ steps.deployment_vars.outputs.dotnet_project }}
      service_name: ${{ steps.deployment_vars.outputs.service_name }}
      dockerfile_path: ${{ steps.deployment_vars.outputs.dockerfile_path }}
      image_name: ${{ steps.deployment_vars.outputs.image_name }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate deployments details
        run: |
          if [[ ${{ github.ref_name }} != "master" ]]; then
            echo "Esse workflow deve ser executado apenas na branch master"
            exit 1
          fi

      - name: Setup Deployment Variables
        id: deployment_vars
        shell: bash
        run: |
          SLUG="${{ inputs.api_selection }}"


          #Mapeamento: slug | ProjectName | ContainerName
          case $SLUG in
            "Primeira API")     PROJ="PrimeiraAPI";     SVC="primeira-api" ;;
            "Segunda API")     PROJ="SegundaAPI";     SVC="segunda-api" ;;
          esac

          DOTNET_PROJECT="Pipeline.$PROJ"
          DOCKERFILE_PATH="./docker-compose/dockerfiles/$SVC.dockerfile"
          IMAGE_NAME="pipeline/$SVC-api"
          SERVICE_NAME="$SVC"

          echo "DOTNET_PROJECT=$DOTNET_PROJECT" >> "$GITHUB_ENV"
          echo "DOCKERFILE_PATH=$DOCKERFILE_PATH" >> "$GITHUB_ENV"
          echo "IMAGE_NAME=$IMAGE_NAME" >> "$GITHUB_ENV"
          echo "SERVICE_NAME=$SERVICE_NAME" >> "$GITHUB_ENV"

          echo "dotnet_project=$DOTNET_PROJECT" >> "$GITHUB_OUTPUT"
          echo "dockerfile_path=$DOCKERFILE_PATH" >> "$GITHUB_OUTPUT"
          echo "image_name=$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "service_name=$SERVICE_NAME" >> "$GITHUB_OUTPUT"

      - name: Validate Changelog text
        shell: bash
        run: |
          version="${{ inputs.api_version }}"
          

          changelog_path="$DOTNET_PROJECT/CHANGELOG.md"

          echo "Validando versão: $version no arquivo $changelog_path"

           if [ ! -f "$changelog_path" ]; then
             echo "✗ Arquivo $changelog_path não encontrado"
             exit 1
           fi

          if grep -q "^# \*\*\[$version\]" "$changelog_path"; then
            echo "✓ Versão $version encontrada no CHANGELOG"
          else
            echo "✗ Versão $version NÃO encontrada no CHANGELOG"
            echo "Por favor, adicione a versão ao CHANGELOG do projeto antes de fazer o release"
            exit 1
          fi

  project_build:
    name: Project compilation and tests
    needs: validate_environment
    runs-on: ubuntu-latest
    env:
      DOTNET_PROJECT: ${{ needs.validate_environment.outputs.dotnet_project }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        shell: bash
        run: |
          dotnet restore

      - name: Build project
        shell: bash
        run: |
          dotnet build "./${DOTNET_PROJECT}/${DOTNET_PROJECT}.csproj" -c Release --no-restore

      - name: Unit Tests
        shell: bash
        run: |
          dotnet test "./Tests/Unit/${DOTNET_PROJECT}.UnitTests/${DOTNET_PROJECT}.UnitTests.csproj" -c Release  --no-restore

      - name: Integration Tests
        shell: bash
        run: |
          dotnet test "./Tests/Integration/${DOTNET_PROJECT}.IntegrationTests/${DOTNET_PROJECT}.IntegrationTests.csproj" -c Release  --no-restore
      
  deploy_production:
    name: Deploy to Production
    needs: project_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        shell: bash
        run: |
          docker build -t ${{ needs.validate_environment.outputs.image_name }}:${{ inputs.api_version }} -f ${{ needs.validate_environment.outputs.dockerfile_path }} .
      